name: Continues Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: SSH Goorm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD}}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls
